In [10]:
import numpy as np
import numpy.random as rd

In [4]:
print(np.ones(10))
print(np.zeros(20))
print(np.arange(11, 36))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]


In [9]:
print(np.identity(3))
n1 = np.arange(1, 10).reshape(3,3)
print(n1)
n2 = n1.ravel()
print(n2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [39]:
print(rd.randn(10))
print(rd.randn(2,2))
print(rd.rand(10))

[-1.21718822 -0.95202532 -1.88205447  0.33374662 -2.03507625 -0.2195116
  1.21654969  0.4405595  -1.42904842 -1.04728076]
[[-0.01161737  0.80927939]
 [-1.47291295  0.69967567]]
[0.38917814 0.8868435  0.18181303 0.16165233 0.35281779 0.23587493
 0.29214736 0.25312705 0.88879134 0.83306644]
