In [1]:
import numpy as np

In [2]:
marks = [
    [99, 93, 100],
    [90, 92, 98],
    [95, 89, 88]
]

In [6]:
n1 = np.array(marks)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)

[[ 99  93 100]
 [ 90  92  98]
 [ 95  89  88]]
<class 'numpy.ndarray'>
2
(3, 3)


In [13]:
# indexing
print(n1[0])
print(n1[-1])
print(n1[[0, -1]])
print(n1[0][1]) # in regular python lists. Is not that optimal
print(n1[0, 1]) # numpy way and is optimal
print(n1[[0, -1], 0])

[ 99  93 100]
[95 89 88]
[[ 99  93 100]
 [ 95  89  88]]
93
93
[99 95]


In [18]:
# slicing
print(n1)
print(n1[:2])
print(n1[-2:])
print(n1[:2, -2:])

[[ 99  93 100]
 [ 90  92  98]
 [ 95  89  88]]
[[ 99  93 100]
 [ 90  92  98]]
[[90 92 98]
 [95 89 88]]
[[ 93 100]
 [ 92  98]]


In [22]:
# indexing + slicing
print(n1)
print(n1[[0, -1], :2])
print(n1[:2, [0, -1]])

[[ 99  93 100]
 [ 90  92  98]
 [ 95  89  88]]
[[99 93]
 [95 89]]
[[ 99 100]
 [ 90  98]]


In [25]:
# descriptive statistics
print(n1)
# vertical axis = 0
# horizonatal axis = 1
n2 = n1.mean(axis=0)
print(n2)
n3 = n1.sum(axis=1)
print(n3)

[[ 99  93 100]
 [ 90  92  98]
 [ 95  89  88]]
[94.66666667 91.33333333 95.33333333]
[292 280 272]


In [26]:
# matrix operations
m1 = np.array([
    [2, 4],
    [3, 7]
])
m2 = np.array([
    [7, 2],
    [6, 9]
])
print(m1)
print(m2)

[[2 4]
 [3 7]]
[[7 2]
 [6 9]]


In [30]:
print(m1 + m2)
print(m1 - m2)
print(m1 * m2)
print(np.dot(m1, m2)) # matrix multiplication

[[ 9  6]
 [ 9 16]]
[[-5  2]
 [-3 -2]]
[[14  8]
 [18 63]]
[[38 40]
 [63 69]]
