In [104]:
import numpy as np

In [105]:
marks = [2, 3, 4, 2, 10, 4, 10, 7, 8, 3, 2, 9]

In [106]:
# ndarray
n1 = np.array(marks, dtype=np.int8)
print(type(n1))
print(n1)
print(marks)
print(n1.dtype)
print(n1.shape)
print(n1.ndim)

<class 'numpy.ndarray'>
[ 2  3  4  2 10  4 10  7  8  3  2  9]
[2, 3, 4, 2, 10, 4, 10, 7, 8, 3, 2, 9]
int8
(12,)
1


In [107]:
# indexing (implict 0 based index)
print(n1[0])
print(n1[1])
print(n1[-1])
print(n1[-3])

# multiple indexing
print(n1[[0, -1]])
print(n1[[0, 2, -1]])

2
3
9
3
[2 9]
[2 4 9]


In [108]:
# indexing + modification
n1[0] = 5
print(n1)
n1[[1, -1]] = [2, 8]
print(n1)
n1[[0, -2]] = 0 # broadcasting
print(n1)

[ 5  3  4  2 10  4 10  7  8  3  2  9]
[ 5  2  4  2 10  4 10  7  8  3  2  8]
[ 0  2  4  2 10  4 10  7  8  3  0  8]


In [109]:
# slicing
print(n1)
print(n1[0:3])
print(n1[:3])
print(n1[3:])
print(n1[-4:])
print(n1[-4:-1])

[ 0  2  4  2 10  4 10  7  8  3  0  8]
[0 2 4]
[0 2 4]
[ 2 10  4 10  7  8  3  0  8]
[8 3 0 8]
[8 3 0]


In [110]:
# modifying a slice of data
print(n1)
n1[:3] = 0
print(n1)

[ 0  2  4  2 10  4 10  7  8  3  0  8]
[ 0  0  0  2 10  4 10  7  8  3  0  8]


In [111]:
# Arithmetic operations
print(n1)
n2 = n1 + 1
print(n2)
n3 = n1 ** 2
print(n3)

[ 0  0  0  2 10  4 10  7  8  3  0  8]
[ 1  1  1  3 11  5 11  8  9  4  1  9]
[  0   0   0   4 100  16 100  49  64   9   0  64]


In [112]:
# Relational operations
print(n1)
n4 = n1 == 10
print(n4)
n5 = (n1 == 10) | (n1 < 5)
print(n5)

[ 0  0  0  2 10  4 10  7  8  3  0  8]
[False False False False  True False  True False False False False False]
[ True  True  True  True  True  True  True False False  True  True False]


In [113]:
# filtering
print(n1)
n6 = n1[n1 < 5]
print(n6)
n7 = n1[(n1 == 10) | (n1 < 5)]
print(n7)

[ 0  0  0  2 10  4 10  7  8  3  0  8]
[0 0 0 2 4 3 0]
[ 0  0  0  2 10  4 10  3  0]


In [114]:
# descriptive statistics
print(n1)
print(n1.mean())
print(np.median(n1))
print(n1.std())
print(n1.var())
print(n1.min())
print(n1.max())

[ 0  0  0  2 10  4 10  7  8  3  0  8]
4.333333333333333
3.5
3.8801489089409387
15.055555555555557
0
10


In [115]:
chocolates = np.array([4, 5, 2, 6, 7, 4, 2])
print(chocolates)
print(chocolates.cumsum())
print(chocolates.cumprod())

[4 5 2 6 7 4 2]
[ 4  9 11 17 24 28 30]
[    4    20    40   240  1680  6720 13440]


In [116]:
print(chocolates.sum())
print(chocolates.shape[0])

30
7


In [117]:
# unique elements
print(n1)
print(np.unique(n1))
# sorted
print(np.sort(n1))
print(n1)

[ 0  0  0  2 10  4 10  7  8  3  0  8]
[ 0  2  3  4  7  8 10]
[ 0  0  0  0  2  3  4  7  8  8 10 10]
[ 0  0  0  2 10  4 10  7  8  3  0  8]


In [119]:
print(n1)
labeled = np.where(n1 > 7, 1, 0)
print(labeled)

[ 0  0  0  2 10  4 10  7  8  3  0  8]
[0 0 0 0 1 0 1 0 1 0 0 1]
